apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: techtrends 
  namespace: techtrends-staging
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd/techtrends-manifests
    repoURL: https://github.com/bilsteol/nd064_course_1
    targetRevision: HEAD
  source:
    helm:
      valueFiles:
      - values-staging.yaml
    path: helm
    repoURL: https://github.com/udacity/nd064_course_1 
    targetRevision: HEAD    
  syncPolicy: {}