namespace:
  name: staging
 
service:
  port: 5111
  targetPort: 3111
  protocol: TCP
  type: ClusterIP

image:
  registry: docker.io
  repository: bilsteol/techtrends 
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 3
containerPort: 3111

livenessProbePath: /healthz
readinessProbePath: /healthz

resources:
  requests:
    memory: "90Mi"
    cpu: "300m"

  limits:
    memory: "128Mi"
    cpu: "500m"
