namespace:
  name: prod
 
service:
  port: 7111
  targetPort: 3111
  protocol: TCP
  type: ClusterIP

image:
  registry: docker.io
  repository: bilsteol/techtrends 
  tag: latest
  pullPolicy: Always

replicaCount: 5
containerPort: 7111

resources:
  requests:
    memory: "128Mi"
    cpu: "350m"

  limits:
    memory: "256Mi"
    cpu: "500m"
